// common
const cssPropTypes = {
  container: 'Boolean',
  display: 'String',
  clearfix: 'Boolean',
  float: 'String',
  objectFit: 'String',
  objectPosition: 'String',
  overflow: 'String',
  overflowX: 'String',
  overflowY: 'String',
  scrolling: 'String',
  position: 'String',
  inset: 'String',
  insetX: 'Boolean',
  insetY: 'Boolean',
  pin: 'Object',
  visible: 'Boolean',
  zIndex: ['String', 'Number'],
  borderColor: 'String',
  borderStyle: 'String',
  borderWidth: ['String', 'Number'],
  borderRadius: ['String', 'Boolean'],
  width: ['String', 'Number'],
  minWidth: ['String', 'Number'],
  maxWidth: 'String',
  height: ['String', 'Number'],
  minHeight: ['String', 'Number'],
  maxHeight: 'String',
  color: 'String',
  fontFamily: 'String',
  fontSize: 'String',
  fontSmoothing: ['String', 'Boolean'],
  fontStyle: 'String',
  fontWeight: 'String',
  letterSpacing: 'String',
  lineHeight: 'String',
  listType: 'String',
  listPosition: 'String',
  textAlignX: 'String',
  textAlignY: 'String',
  textDecoration: 'String',
  textTransform: 'String',
  whitespace: 'String',
  wordBreak: 'String',
  flex: ['String', 'Number'],
  flexDirection: 'String',
  flexWrap: ['String', 'Boolean'],
  alignItems: 'String',
  alignContent: 'String',
  alignSelf: 'String',
  justifyContent: 'String',
  flexGrow: 'Boolean',
  flexShrink: 'Boolean',
  flexOrder: ['String', 'Number'],
  tableCollapse: 'String',
  tableLayout: 'String',
  bgAttachment: 'String',
  bgColor: 'String',
  bgPosition: 'String',
  bgRepeat: 'String',
  bgSize: 'String',
  padding: ['Number', 'String', 'Object'],
  margin: ['Number', 'String', 'Object'],
  appearance: 'String',
  cursor: 'String',
  outline: 'String',
  pointerEvents: 'String',
  resize: ['String', 'Boolean'],
  userSelect: 'String',
  shadow: 'String',
  opacity: 'String',
  fill: 'Boolean',
  stroke: 'Boolean',
}
const bit = [true, false]
const colorNames = [
  'transparent',
  'black',
  'white',
  'gray',
  'red',
  'orange',
  'yellow',
  'green',
  'teal',
  'blue',
  'indigo',
  'purple',
  'pink',
]
const colorRange = [100, 200, 300, 400, 500, 600, 700, 800, 900]
const colors = [colorNames, colorRange]
// layout
const overflows = ['auto', 'hidden', 'visible', 'scroll']
const layoutProps = {
  container: bit,
  sizes: ['none', 'sm', 'md', 'lg', 'xl'],
  display: [
    'hidden',
    'block',
    'inline-block',
    'flex',
    'inline-flex',
    'inline',
    'table',
    'table-row',
    'table-cell',
  ],
  clearfix: bit,
  float: ['none', 'left', 'right'],
  objectFit: ['none', 'contain', 'cover', 'fill', 'scale-down'],
  objectPosition: [
    'bottom',
    'center',
    'left',
    'left-bottom',
    'left-top',
    'right',
    'right-bottom',
    'right-top',
    'top',
  ],
  overflow: overflows,
  overflowX: overflows,
  overflowY: overflows,
  scrolling: ['auto', 'touch'],
  position: ['static', 'fixed', 'absolute', 'relative', 'sticky'],
  inset: bit,
  inset: bit,
  insetY: bit,
  pin: { top: bit, right: bit, bottom: bit, left: bit },
  visible: bit,
  zIndex: ['auto', 0, 10, 20, 30, 40, 50],
}
// borders
const borderSizes = [0, 1, 2, 4, 8]
const radius = [bit, 'none', 'sm', 'lg', 'full']
const borderProps = {
  color: colors,
  style: ['solid', 'dashed', 'dotted', 'none'],
  size: {
    all: borderSizes,
    top: borderSizes,
    left: borderSizes,
    right: borderSizes,
    bottom: borderSizes,
  },
  radius: {
    all: radius,
    top: radius,
    left: radius,
    right: radius,
    bottom: radius,
    topLeft: radius,
    topRight: radius,
    bottomLeft: radius,
    bottomRight: radius,
  },
}
// sizing
const sizes = [
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  8,
  10,
  12,
  16,
  20,
  24,
  32,
  40,
  48,
  56,
  64,
  'auto',
  'px',
  '1/2',
  '1/3',
  '2/3',
  '1/4',
  '2/4',
  '3/4',
  '1/5',
  '2/5',
  '3/5',
  '4/5',
  '1/6',
  '2/6',
  '3/6',
  '4/6',
  '5/6',
  '1/12',
  '2/12',
  '3/12',
  '4/12',
  '5/12',
  '6/12',
  '7/12',
  '8/12',
  '9/12',
  '10/12',
  '11/12',
  'full',
  'screen',
]
const sizingProps = {
  width: sizes,
  minWidth: [0, 'full'],
  maxWidth: [
    'xs',
    'sm',
    'md',
    'lg',
    'xl',
    '2xl',
    '3xl',
    '4xl',
    '5xl',
    '6xl',
    'full',
  ],
  height: sizes,
  minHeight: [0, 'full', 'screen'],
  maxHeight: ['full', 'screen'],
}
// typography
const typoProps = {
  color: colors,
  family: ['sans', 'serif', 'mono'],
  size: ['base', 'xs', 'sm', 'lg', 'xl', '2xl', '3xl', '4xl', '5xl', '6xl'],
  smoothing: [true, ' sub-pixel'],
  style: ['normal', 'italic'],
  weight: [
    'hairline',
    'thin',
    'light',
    'normal',
    'medium',
    'semi',
    'bold',
    'extra',
    'black',
  ],
  letterSpacing: ['tighter', 'tight', 'normal', 'wide', 'wider', 'widest'],
  lineHeight: ['none', 'tight', 'snug', 'normal', 'relaxed', 'loose'],
  listType: ['none', 'disc', 'decimal'],
  listPosition: ['inside', 'outside'],
  align: {
    horizontal: ['left', 'center', 'right', 'justify'],
    vertical: [
      'baseline',
      'top',
      'middle',
      'bottom',
      'text-top',
      'text-bottom',
    ],
  },
  decoration: ['none', 'line-through', 'underline'],
  transform: ['uppercase', 'lowercase', 'capitalize', 'normal'],
  whitespace: ['normal', 'no-wrap', 'pre', 'pre-line', 'pre-wrap'],
  break: ['normal', 'words', 'all', 'truncate'],
}
// flexbox
const flexPos = ['start', 'center', 'end', 'between', 'around']
const flexProps = {
  flex: [1, 'auto', 'initial', 'none'],
  direction: ['row', 'row-reverse', 'col', 'col-reverse'],
  wrap: [bit, 'reverse'],
  alignItems: ['stretch', 'start', 'center', 'end', 'baseline'],
  alignContent: flexPos,
  alignSelf: ['auto', 'start', 'center', 'end', 'stretch'],
  justifyContent: flexPos,
  grow: bit,
  shrink: bit,
  order: ['first', 'last', 'none', 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1],
}
// tables
const tableProps = {
  tableCollapse: ['collapse', 'separate'],
  tableLayout: ['auto', 'fixed'],
}
// backgrounds
const bgProps = {
  attachment: ['fixed', 'local', 'scroll'],
  color: colors,
  position: [
    'bottom',
    'center',
    'left',
    'left-bottom',
    'left-top',
    'right',
    'right-bottom',
    'right-top',
    'top',
  ],
  repeat: ['repeat', 'no-repeat', 'x', 'y', 'round', 'space'],
  size: ['auto', 'cover', 'contain'],
}
// spacing
const paddingRange = [
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  8,
  10,
  12,
  16,
  20,
  24,
  32,
  40,
  48,
  56,
  64,
  'px',
]
const marginRange = [
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  8,
  10,
  12,
  16,
  20,
  24,
  32,
  40,
  48,
  56,
  64,
  'auto',
  'px',
]
const spacingProps = {
  padding: {
    all: paddingRange,
    x: paddingRange,
    y: paddingRange,
    top: paddingRange,
    right: paddingRange,
    bottom: paddingRange,
    left: paddingRange,
  },
  margin: {
    all: marginRange,
    x: marginRange,
    y: marginRange,
    top: marginRange,
    right: marginRange,
    bottom: marginRange,
    left: marginRange,
  },
}
// interactivity
const interactProps = {
  appearance: ['none'],
  cursor: ['auto', 'default', 'pointer', 'wait', 'text', 'move', 'not-allowed'],
  outline: ['none'],
  pointerEvents: ['none', 'auto'],
  resize: [bit, 'x', 'y'],
  userSelect: ['none', 'text', 'all', 'auto'],
}

