export const styles = {
  lineBlock: 'lineBlock',
  highlightBottomLeftCorner: 'highlightBottomLeftCorner',
  highlightTopLeftCorner: 'highlightTopLeftCorner',
  highlightLineVertical: 'highlightLineVertical',
  absoluteLineBlock: 'absoluteLineBlock',
  collapseButton: 'collapseButton',
  expandButton: 'expandButton',
  rowWrapper: 'rowWrapper',
  rowWrapperDragDisabled: 'rowWrapperDragDisabled',
  row: 'row',
  rowLandingPad: 'rowLandingPad',
  rowCancelPad: 'rowCancelPad',
  rowSearchMatch: 'rowSearchMatch',
  rowSearchFocus: 'rowSearchFocus',
  rowContents: 'rowContents',
  rowContentsDragDisabled: 'rowContentsDragDisabled',
  rowToolbar: 'rowToolbar',
  toolbarButton: 'toolbarButton',
  rowLabel: 'rowLabel',
  rowTitle: 'rowTitle',
  subtitle: 'subtitle',
  rowTitleWithSubtitle: 'rowTitleWithSubtitle',
  rowSubtitle: 'rowSubtitle',
  lineChildren: 'lineChildren',
}